# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExcalidrawConverter < Formula
  desc "A command line tool for porting Excalidraw diagrams to Gliffy."
  homepage "https://github.com/sindrel/excalidraw-converter"
  version "1.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.5.5/excalidraw-converter_1.5.5_darwin_amd64.tar.gz"
      sha256 "6181ac9c4ff655c6fc5889256d6a86096a88e243cf875a053018f571b23a9589"

      define_method(:install) do
        bin.install "exconv"
        bin.install_symlink "#{bin}/exconv" => "excalidraw-converter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.5.5/excalidraw-converter_1.5.5_darwin_arm64.tar.gz"
      sha256 "67860d1282606f899f0d5f4737c6640329b4a61924434046818787d9512e6d6e"

      define_method(:install) do
        bin.install "exconv"
        bin.install_symlink "#{bin}/exconv" => "excalidraw-converter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.5.5/excalidraw-converter_1.5.5_linux_amd64.tar.gz"
      sha256 "9137d465fd8c2f89e54302c6d4852999d0633ccaca2822de09e9d4c7c6b24b52"
      define_method(:install) do
        bin.install "exconv"
        bin.install_symlink "#{bin}/exconv" => "excalidraw-converter"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.5.5/excalidraw-converter_1.5.5_linux_armv6.tar.gz"
      sha256 "c84e4f52917de2457cb741f40752624b7552c7b3994fc3af7f7cc77811fc00a7"
      define_method(:install) do
        bin.install "exconv"
        bin.install_symlink "#{bin}/exconv" => "excalidraw-converter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.5.5/excalidraw-converter_1.5.5_linux_arm64.tar.gz"
      sha256 "19e13c36dc951547bd67a294e3d3364672a7e586df03c2f0ca7d9cf08b2b7495"
      define_method(:install) do
        bin.install "exconv"
        bin.install_symlink "#{bin}/exconv" => "excalidraw-converter"
      end
    end
  end

  test do
    system "#{bin}/exconv version"
  end
end
