# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExcalidrawConverter < Formula
  desc "A command line tool for porting Excalidraw diagrams to Gliffy."
  homepage "https://github.com/sindrel/excalidraw-converter"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.0.5/excalidraw-converter_1.0.5_darwin_amd64.tar.gz"
      sha256 "d91cc5ec0daa2aca8ef0853a774e5e284ba3df32708637c0f4430f356486062f"

      def install
        bin.install "exconv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.0.5/excalidraw-converter_1.0.5_darwin_arm64.tar.gz"
      sha256 "5e8d2dcef94ebf59b241321a134baa6250117e26783737f7bf51ccee07fbccf3"

      def install
        bin.install "exconv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.0.5/excalidraw-converter_1.0.5_linux_arm64.tar.gz"
      sha256 "f33a452f1e02231222c178238e1f97becf03de5e4f0fa32119497e474db55cee"

      def install
        bin.install "exconv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.0.5/excalidraw-converter_1.0.5_linux_amd64.tar.gz"
      sha256 "db2e1894682e77e2d2f1220f2cee322e95ddc2c97a4a2fc55f305e1428f765b1"

      def install
        bin.install "exconv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sindrel/excalidraw-converter/releases/download/v1.0.5/excalidraw-converter_1.0.5_linux_armv6.tar.gz"
      sha256 "526434824b2533dc713954f3d90c060a2b64ac71c7c0c88b840f32492d603a18"

      def install
        bin.install "exconv"
      end
    end
  end

  test do
    system "#{bin}/exconv version"
  end
end
